In [1]:
!pip install selenium

You should consider upgrading via the 'c:\users\asus\anaconda3\python.exe -m pip install --upgrade pip' command.


In [2]:
!pip install beautifulsoup4 --quiet

You should consider upgrading via the 'c:\users\asus\anaconda3\python.exe -m pip install --upgrade pip' command.


In [3]:
import os
import pandas as pd
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
from gensim.models import Word2Vec
from tqdm.auto import tqdm

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
C:\Users\ASUS\anaconda3\lib\site-packages\requests\__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)


In [4]:
from selenium import webdriver
options = webdriver.ChromeOptions()
options.add_experimental_option('prefs', {'intl.accept_languages': 'id'})
driver = webdriver.Chrome(executable_path="E:/apps/chromedriver.exe",chrome_options=options)

C:\Users\ASUS\anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  after removing the cwd from sys.path.
C:\Users\ASUS\anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: use options instead of chrome_options
  after removing the cwd from sys.path.


In [6]:
url = 'https://www.google.com/maps/place/Mie+Gacoan+Kotabaru/@-7.7884815,110.3751255,15z/data=!4m5!3m4!1s0x0:0x6330d678abba8199!8m2!3d-7.7885279!4d110.3751087'
driver.get(url)

In [7]:
import time
time.sleep(3)

In [8]:
#Find the total number of reviews
# total_number_of_reviews = driver.find_element_by_xpath('//*[@id="pane"]/div/div[1]/div/div/div[27]/div/div[2]/button').text.split(" ")[0]
# total_number_of_reviews = int(float(total_number_of_reviews.replace('.',''))) if ',' in total_number_of_reviews else int(total_number_of_reviews)
total_number_of_reviews=1861
#Find scroll layout
scrollable_div = driver.find_element_by_xpath('//*[@id="pane"]/div/div[1]/div/div/div[2]')
#Scroll as many times as necessary to load all reviews
for i in range(0,(round(total_number_of_reviews/10 - 1))):
        driver.execute_script('arguments[0].scrollTop = arguments[0].scrollHeight',scrollable_div)
        time.sleep(1)

C:\Users\ASUS\anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  


KeyboardInterrupt: 

In [ ]:
def get_review_summary(result_set):
    rev_dict = {'Review_Rate': [],
        'Review_Time': [],
        'Review_Text' : []}
    for result in result_set:
        review_rate = result.find('span', class_='ODSEW-ShBeI-H1e3jb')["aria-label"]
        review_time = result.find('span',class_='ODSEW-ShBeI-RgZmSc-date').text
        review_text = result.find('span',class_='ODSEW-ShBeI-text').text
        rev_dict['Review_Rate'].append(review_rate)
        rev_dict['Review_Time'].append(review_time)
        rev_dict['Review_Text'].append(review_text)
    import pandas as pd    
    return(pd.DataFrame(rev_dict))

In [ ]:
from bs4 import BeautifulSoup
response = BeautifulSoup(driver.page_source, 'html.parser')
reviews = response.find_all('div', class_='ODSEW-ShBeI NIyLF-haAclf gm2-body-2')

In [ ]:
b=get_review_summary(reviews)

In [ ]:
df_kobar=pd.DataFrame(b)

In [68]:
df_kobar.head(40)

Review_Rate    Review_Time  \
0   4 bintang   4 minggu lalu   
1   5 bintang   3 minggu lalu   
2   5 bintang   2 minggu lalu   

                                         Review_Text  
0  Tempat makan mie dengan berbagai kreasi pedas....  
1  Pas kesana jam 11 siang, awal dateng masih sep...  
2  Syuper selalu ramai resto satu ini,entah yang ...

In [20]:
a=get_review_summary(reviews)

In [21]:
df=pd.DataFrame(a)

In [22]:
df.head(10)

Review_Rate    Review_Time  \
0   5 bintang   2 minggu lalu   
1   5 bintang   2 minggu lalu   
2   5 bintang    2 bulan lalu   
3   4 bintang    2 bulan lalu   
4   1 bintang    2 bulan lalu   
5   1 bintang   2 minggu lalu   
6   4 bintang   3 minggu lalu   
7   5 bintang    2 bulan lalu   
8   1 bintang   seminggu lalu   
9   5 bintang   seminggu lalu   

                                         Review_Text  
0  Ini cocok banget buat yg suka pedass , level b...  
1  Seneng banget di gacoan sini antrinya ga seram...  
2  Enakk bangett, tapi recommended siomay nya, ha...  
3  Warung mie yg selalu rame sama ojol+mahasiswa....  
4  9 September 2021 pukul 19.00, Saya sedang saki...  
5  Pemerintah mati"an memutuskan rantai penyebara...  
6  Mie nya udah gausah diragukan lagi, enak bange...  
7  Mie kekinian yang berada di jalan Colombo. Ada...  
8  Antrinya lama.banyak driver ojol menumpuk jadi...  
9  Berkunjung ke Jogja untuk urusan pekerjaan, da...

In [28]:
df['rating']=[Review_Rate.replace(' bintang','') for Review_Rate in df.Review_Rate]

In [37]:
from IPython.display import FileLink, FileLinks

df.to_csv('E:/tugas koko/SEMESTER5/Data Engineering/Tugas/Tugas Akhir/Gacoan_data.csv', index=False)

In [30]:
df.drop('Review_Rate', axis=1, inplace=True)

In [36]:
df.head(5)

Review_Time                                        Review_Text rating
0  2 minggu lalu  Ini cocok banget buat yg suka pedass , level b...      5
1  2 minggu lalu  Seneng banget di gacoan sini antrinya ga seram...      5
2   2 bulan lalu  Enakk bangett, tapi recommended siomay nya, ha...      5
3   2 bulan lalu  Warung mie yg selalu rame sama ojol+mahasiswa....      4
4   2 bulan lalu  9 September 2021 pukul 19.00, Saya sedang saki...      1

In [35]:
df['rating']=[rating.replace(' ','') for rating in df.rating]

In [43]:
df['rating']=df['rating'].astype(int)

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Review_Time  930 non-null    object
 1   Review_Text  930 non-null    object
 2   rating       930 non-null    int32 
dtypes: int32(1), object(2)
memory usage: 18.3+ KB


# Word Embedding

## A. Word2Vec

In [89]:
rev_list=[word_tokenize(Review_Text.lower()) for Review_Text in tqdm(df.Review_Text)]

In [95]:
print(rev_list[:2])

[['ini', 'cocok', 'banget', 'buat', 'yg', 'suka', 'pedass', ',', 'level', 'bisa', 'milih', 'sendiri', 'mau', 'yg', 'pedas', 'nya', 'sedang', 'atau', 'pedas', 'banget', 'bisa', ',', 'pokok', 'nya', 'mie', 'pedas', 'nomer', '1', 'di', 'indonesia', 'lah', ',', 'egga', 'usah', 'diragukan', 'lagi', 'soal', 'rasa', '👍👍', ',', 'kalau', 'saya', 'sih', 'suka', 'nya', 'pesan', 'mie', '…'], ['seneng', 'banget', 'di', 'gacoan', 'sini', 'antrinya', 'ga', 'serame', 'cabang', 'lain', ',', 'walaupun', 'agak', 'lama', 'nunggu', 'makananya', 'tapi', 'its', 'okeyyy🥰']]


## 1. CBOW Model

In [96]:
model= Word2Vec(rev_list, vector_size=128,window=5,min_count=3, workers=4, sg=0,hs=0,epochs=1000)

### 1.1 Save

In [97]:
model.save('E:/tugas koko/SEMESTER5/Natural Language Processing/Materi/Self Learning/model.w2v')

### 1.2 Load

In [98]:
model=Word2Vec.load('E:/tugas koko/SEMESTER5/Natural Language Processing/Materi/Self Learning/model.w2v')

In [99]:
"Rasanya enak banget, gaada duanya. Mienya mantap sekali".split()

['Rasanya',
 'enak',
 'banget,',
 'gaada',
 'duanya.',
 'Mienya',
 'mantap',
 'sekali']

In [100]:
contoh=['Rasanya',
 'enak',
 'banget,',
 'gaada',
 'duanya.',
 'Mienya',
 'mantap',
 'sekali']

In [101]:
model.train(contoh,total_examples=len(contoh),epochs=100)

(1132, 4800)

### 1.3 Informasi Mengenai Model

In [102]:
w2v=model.wv

In [103]:
w2v.index_to_key

[',',
 '.',
 'enak',
 'dan',
 'mie',
 'yang',
 'di',
 'tempat',
 'nya',
 'juga',
 'yg',
 '…',
 'tapi',
 'banget',
 'ada',
 'murah',
 'untuk',
 'tempatnya',
 'buat',
 'makan',
 'harga',
 '...',
 'gacoan',
 'lama',
 'saya',
 'tidak',
 'banyak',
 'sama',
 'nyaman',
 '!',
 'level',
 'rasa',
 'bisa',
 'pelayanan',
 'kalo',
 'dengan',
 'kurang',
 'rame',
 'karena',
 'suka',
 'menu',
 'sangat',
 'ini',
 'pedas',
 'ga',
 'rasanya',
 'pas',
 'mienya',
 'lebih',
 'pedes',
 'aja',
 'lumayan',
 'antri',
 'selalu',
 'iblis',
 'ramah',
 'dari',
 'sih',
 'kalau',
 'jadi',
 'makanan',
 '(',
 'harus',
 'lagi',
 ')',
 'disini',
 'harganya',
 'cocok',
 'ke',
 'cuma',
 'mau',
 'ya',
 'antrian',
 'nunggu',
 '1',
 'terjangkau',
 'udah',
 'udang',
 'bgt',
 'ramai',
 'jam',
 'gak',
 'ojol',
 'pangsit',
 'pelayanannya',
 'setan',
 'mantap',
 '2',
 'luas',
 'panjang',
 'itu',
 'jalan',
 'seperti',
 'es',
 'cepat',
 'antrinya',
 'lantai',
 'mahasiswa',
 ':',
 'sekali',
 'makanannya',
 'tp',
 'nongkrong',
 'palin

In [104]:
w2v.vectors

array([[ 0.65634316,  1.296112  ,  0.79386866, ...,  0.30905268,
         0.3065758 ,  0.41571727],
       [ 0.6820215 ,  0.85354066,  1.2484522 , ..., -0.0915444 ,
         0.7058167 ,  0.16579475],
       [ 0.23501539, -0.01201844, -0.9117624 , ...,  0.4418651 ,
         0.6667651 ,  0.31604496],
       ...,
       [ 2.0477602 ,  1.3629754 , -2.154629  , ..., -3.5601676 ,
        -0.27161282, -3.8095944 ],
       [ 1.0437734 ,  0.7163155 ,  0.77923757, ..., -0.37267613,
         1.6434482 , -2.9327667 ],
       [-0.93736917,  2.0260446 , -2.0354674 , ..., -1.4154307 ,
         1.484429  ,  1.8868454 ]], dtype=float32)

In [105]:
w2v["gacoan"]

array([ 1.3788567 , -1.9610814 , -0.6728882 , -1.196431  ,  0.29502606,
        1.1952976 ,  0.4658618 ,  1.6434201 ,  1.1114185 , -1.8864316 ,
       -2.0505643 , -0.0154541 , -0.7866657 , -0.84674925,  1.1312528 ,
       -1.3442184 , -0.10267678, -2.1823683 ,  1.2876357 , -0.72472614,
        2.0018077 , -1.6288599 , -2.1010344 ,  1.1798083 , -1.9606147 ,
       -0.76741123,  0.9887782 , -1.2828591 ,  0.9317608 ,  2.0678463 ,
       -2.6434274 , -2.2997012 ,  2.5495236 ,  2.510117  ,  1.5571027 ,
        1.6401079 ,  1.0454789 ,  1.8053706 , -0.4327528 , -0.4231073 ,
        0.5308034 ,  1.4499336 , -4.6716604 ,  1.8828235 , -1.1653793 ,
        0.3708856 , -1.799949  ,  1.6746137 , -0.7201362 , -0.8420724 ,
       -0.9857133 ,  0.00490928, -1.9721124 ,  2.3832448 ,  1.4630283 ,
       -0.8456958 ,  1.444545  ,  0.39143008,  2.3901196 , -0.02408816,
       -0.32913432, -2.8269842 , -0.6112656 ,  1.0605174 , -0.36885145,
        0.60996574, -2.3830361 ,  2.5449564 , -2.4209778 ,  0.25

### 1.4 Sanity Check Similar Word

In [106]:
w2v.similar_by_word("gacoan")

[('guys', 0.2548476457595825),
 ('ingin', 0.2532208263874054),
 ('jalan', 0.2428692728281021),
 ('kuliner', 0.23107992112636566),
 ('berada', 0.2231818586587906),
 ('sistemnya', 0.22300638258457184),
 ('kunjungan', 0.2121029496192932),
 ('temen', 0.2084004431962967),
 ('hehehe', 0.20669205486774445),
 ('namun', 0.20018386840820312)]

In [107]:
w2v.similar_by_word("antri")

[('antrian', 0.4088410437107086),
 ('ngantri', 0.4009838402271271),
 ('20', 0.3439447581768036),
 ('ber', 0.31966352462768555),
 ('antrinya', 0.3004263937473297),
 ('via', 0.29066401720046997),
 ('antriannya', 0.2740960121154785),
 ('driver', 0.27225667238235474),
 ('&', 0.26036033034324646),
 ('parkir', 0.24774713814258575)]

### 1.5 Visualize

In [108]:
from umap import UMAP
import numpy as np
import plotly.express as px

In [109]:
X=UMAP().fit_transform(w2v.vectors)

In [131]:
data=pd.DataFrame(X, columns=["umaps1","umaps2"])
data["text"]=w2v.index_to_key
data

umaps1    umaps2     text
0    6.992421  4.091777        ,
1    6.335091  3.695102        .
2    6.915115  4.728464     enak
3    5.974349  4.106518      dan
4    7.446612  5.029146      mie
..        ...       ...      ...
827  6.148220  1.974379     jaga
828  7.094151  4.297982    tiada
829  6.891730  3.290268    somay
830  8.198983  2.362659  mencoba
831  7.187693  2.965299   enakkk

[832 rows x 3 columns]

In [132]:
fig=px.scatter(data, x="umaps1", y="umaps2", text="text")
fig.update_traces(textposition="top center")
fig.update_layout(
    height=800,
    title_text="Visualisasi Word2Vec"
    )
fig.show()

## 2. Skip-Gram Model

In [112]:
model1= Word2Vec(rev_list, vector_size=128,window=5,min_count=3, workers=4, sg=1,hs=0)

In [113]:
model1.save('E:/tugas koko/SEMESTER5/Natural Language Processing/Materi/Self Learning/model1.w2v')

In [114]:
model1=Word2Vec.load('E:/tugas koko/SEMESTER5/Natural Language Processing/Materi/Self Learning/model1.w2v')

In [115]:
w2v1=model1.wv

In [116]:
w2v1.index_to_key

[',',
 '.',
 'enak',
 'dan',
 'mie',
 'yang',
 'di',
 'tempat',
 'nya',
 'juga',
 'yg',
 '…',
 'tapi',
 'banget',
 'ada',
 'murah',
 'untuk',
 'tempatnya',
 'buat',
 'makan',
 'harga',
 '...',
 'gacoan',
 'lama',
 'saya',
 'tidak',
 'banyak',
 'sama',
 'nyaman',
 '!',
 'level',
 'rasa',
 'bisa',
 'pelayanan',
 'kalo',
 'dengan',
 'kurang',
 'rame',
 'karena',
 'suka',
 'menu',
 'sangat',
 'ini',
 'pedas',
 'ga',
 'rasanya',
 'pas',
 'mienya',
 'lebih',
 'pedes',
 'aja',
 'lumayan',
 'antri',
 'selalu',
 'iblis',
 'ramah',
 'dari',
 'sih',
 'kalau',
 'jadi',
 'makanan',
 '(',
 'harus',
 'lagi',
 ')',
 'disini',
 'harganya',
 'cocok',
 'ke',
 'cuma',
 'mau',
 'ya',
 'antrian',
 'nunggu',
 '1',
 'terjangkau',
 'udah',
 'udang',
 'bgt',
 'ramai',
 'jam',
 'gak',
 'ojol',
 'pangsit',
 'pelayanannya',
 'setan',
 'mantap',
 '2',
 'luas',
 'panjang',
 'itu',
 'jalan',
 'seperti',
 'es',
 'cepat',
 'antrinya',
 'lantai',
 'mahasiswa',
 ':',
 'sekali',
 'makanannya',
 'tp',
 'nongkrong',
 'palin

In [117]:
w2v1.vectors

array([[ 0.01784046, -0.1436965 ,  0.07002604, ..., -0.03291371,
         0.0389524 ,  0.01303762],
       [ 0.0249634 , -0.13827364,  0.073351  , ..., -0.0387489 ,
         0.03035777,  0.00551135],
       [ 0.02162514, -0.14865577,  0.05924699, ..., -0.02313437,
         0.04489835,  0.01183431],
       ...,
       [ 0.01738358, -0.0923705 ,  0.03603372, ..., -0.02598977,
         0.03161936,  0.0012766 ],
       [ 0.01515928, -0.10793081,  0.04254896, ..., -0.02083017,
         0.03347828,  0.00234126],
       [ 0.01477512, -0.09939106,  0.03856624, ..., -0.02229939,
         0.02962701,  0.01099722]], dtype=float32)

In [118]:
w2v1["gacoan"]

array([ 4.31545116e-02, -1.41944915e-01,  6.93274438e-02, -4.74892966e-02,
        8.84508044e-02,  1.25063676e-02,  6.17633872e-02, -3.70032974e-02,
       -1.58515442e-02,  9.25409719e-02,  1.80300504e-01,  3.92804891e-02,
       -4.02238555e-02, -2.02501193e-01,  1.63492769e-01,  1.76088095e-01,
        1.69620989e-03, -5.03219813e-02, -9.93738100e-02,  1.47277594e-01,
        2.86437608e-02,  2.40625087e-02, -1.02155335e-01, -3.23564440e-01,
       -2.39841580e-01,  1.29854098e-01, -1.51228234e-01,  6.35892525e-02,
        1.04669137e-02, -9.50416774e-02,  1.83416251e-02, -2.05422547e-02,
       -7.74812791e-03,  6.14010245e-02,  2.25948561e-02,  1.36668369e-01,
        1.90458000e-01, -1.83814257e-01,  6.54417425e-02, -6.08978085e-02,
       -4.38585617e-02,  8.31798688e-02, -7.14503750e-02, -2.51395434e-01,
        2.87906170e-01, -3.50064449e-02, -1.66509971e-01, -5.48254959e-02,
       -8.26746672e-02,  2.86243968e-02,  2.17327029e-01,  1.87691078e-02,
       -1.18007092e-02,  

## B. Fast Text (Another method to transform word into vector)

Fast Text memiliki kemampuan untuk mengidentifikasi kata-kata yang sebenarnya tidak visibel dalam Vocab. Contoh, hanya terdapat kata "Katak", maka Fast Text dapat identifikasi Kata "Kat", "Tak", "Ka", dan "ak". Ini terjadi karena Fast Text menganggap bahwa setiap kata itu terdiri dari character n-gram.

In [119]:
from gensim.models import FastText

In [120]:
model_FastText= FastText(rev_list, vector_size=128,window=5,min_count=3, workers=4, sg=0,hs=0,epochs=1000)

In [122]:
model_FastText.save('E:/tugas koko/SEMESTER5/Natural Language Processing/Materi/Self Learning/model_FastText.fasttext')

In [123]:
model_FastText=FastText.load('E:/tugas koko/SEMESTER5/Natural Language Processing/Materi/Self Learning/model_FastText.fasttext')

In [124]:
model_FastText.train(contoh,total_examples=len(contoh),epochs=100)

(1132, 4800)

In [125]:
FT=model_FastText.wv

In [128]:
FT["manteuppp"]

array([-0.08166686,  0.14563105, -1.317227  ,  0.22473341,  0.31825936,
        0.21295002,  0.43141308,  0.68661374, -0.52451265, -0.04304484,
       -0.5611019 ,  0.6381658 ,  0.46689704,  0.27870026, -0.4765616 ,
       -0.12900738,  0.7406023 ,  0.7177219 ,  0.577295  , -0.02139575,
        0.5415555 , -1.2065607 , -1.4240415 , -0.39121234, -0.76200837,
        0.16203332, -0.53379464, -0.13253266, -0.6152308 , -0.52784455,
       -0.08696921,  0.10950053,  1.3317184 , -0.9117968 ,  0.03030269,
       -0.19062822,  1.5767692 ,  1.1738563 , -0.26801136, -1.0652311 ,
        0.18848285, -0.10762731,  1.0076721 ,  0.3213897 , -0.35262683,
       -0.6009382 ,  0.64582413, -0.43456143,  0.39452383,  0.50387144,
        0.57501227,  0.07199392,  1.4405389 ,  0.4970151 ,  1.0350276 ,
       -0.7671831 , -1.0427809 , -0.5534675 ,  0.05913451, -0.12265854,
        0.36924803, -0.6498404 , -0.8115254 , -0.05910211,  0.19831197,
       -0.16402206, -1.0489733 ,  0.16882484, -0.525218  ,  0.17

In [129]:
FT.similar_by_word("manteupp",topn=5)

[('mantep', 0.9287956953048706),
 ('mantab', 0.7225779294967651),
 ('mantul', 0.7130924463272095),
 ('mantapp', 0.7026000022888184),
 ('mantap', 0.5938747525215149)]

In [130]:
T=UMAP().fit_transform(FT.vectors)

In [134]:
data_Fast=pd.DataFrame(T, columns=["umaps1","umaps2"])
data_Fast["text"]=FT.index_to_key
data_Fast

umaps1    umaps2     text
0    6.574229  4.811860        ,
1    6.554909  4.835432        .
2    5.651223  6.121196     enak
3    6.533400  5.113724      dan
4    5.661474  7.200739      mie
..        ...       ...      ...
827  8.573554  6.996436     jaga
828  6.629521  8.665250    tiada
829  5.917692  6.634565    somay
830  6.537818  8.656266  mencoba
831  5.542774  6.274320   enakkk

[832 rows x 3 columns]

In [135]:
fig=px.scatter(data_Fast, x="umaps1", y="umaps2", text="text")
fig.update_traces(textposition="top center")
fig.update_layout(
    height=800,
    title_text="Visualisasi FastText"
    )
fig.show()